spring:
  application:
    name: WingSpringBoot
  main:
    web-application-type: servlet
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      enable_lazy_load_no_trans: true
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
    username: edu
    password: edu12

server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    uri-encoding: UTF-8

# 외부 이미지 경로 설정 추가
external:
  image:
    path: C:/upload/